---
- name: copy influxdb config to remote dir    
  copy: 
    src: influxdb.conf
    dest: /etc/influxdb/
  notify: restart influxdb
     
- name: copy typesdb to remote dir   
  copy: 
    src: types.db
    dest: /etc/influxdb/
  notify: restart influxdb

- name: Start the InfluxDB service
  systemd: 
    name: influxdb 
    state: started
    enabled: yes
